@extends('master')

@section('content')
Its mission - to explore strange new worlds to seek out new life and new civilizations to boldly go where no man has gone before. Come and play. Everything's A-OK. Friendly neighbors there that's where we meet. Can you tell me how to get how to get to Sesame Street. The Brady Bunch the Brady Bunch that's the way we all became the Brady Bunch. It's time to play the music. It's time to light the lights. It's time to meet the Muppets on the Muppet Show tonight. These Happy Days are yours and mine Happy Days. Come and dance on our floor. Take a step that is new. We've a loveable space that needs your face threes company too. Doin' it our way. There's nothing we wont try. Never heard the word impossible. This time there's no stopping us.<br>
<br>
Got kind of tired packin' and unpackin' - town to town and up and down the dial. Come and play. Everything's A-OK. Friendly neighbors there that's where we meet. Can you tell me how to get how to get to Sesame Street.
<br>
The mate was a mighty sailin' man the Skipper brave and sure. Five passengers set sail that day for a three hour tour a three hour tour. Doin' it our way. There's nothing we wont try. Never heard the word impossible. This time there's no stopping us. And if you threw a party - invited everyone you knew. You would see the biggest gift would be from me and the card attached would say thank you for being a friend." They're creepy and they're kooky mysterious and spooky. They're all together ooky the Addams Family. It's time to put on makeup. It's time to dress up right. It's time to raise the curtain on the Muppet Show tonight? So lets make the most of this beautiful day. Since we're together Didn't need no welfare states. Everybody pulled his weight. Gee our old Lasalle ran great. Those were the days. Well the first thing you know ol' Jeds a millionaire. Kinfolk said Jed move away from there. These Happy Days are yours and mine Happy Days.<br>
<br>
Doin' it our way. There's nothing we wont try. Never heard the word impossible. This time there's no stopping us. Flying away on a wing and a prayer. Who could it be? Believe it or not its just me. The ship set ground on the shore of this uncharted desert isle with Gilligan the Skipper too the millionaire and his wife. Straightnin' the curves. Flatnin' the hills Someday the mountain might get ‘em but the law never will. Flying away on a wing and a prayer. Who could it be? Believe it or not its just me. All of them had hair of gold like their mother the youngest one in curls. Believe it or not I'm walking on air. I never thought I could feel so free?<br>
<br>
Thank you for being a friend. Travelled down the road and back again. Your heart is true you're a pal and a confidant. Come and play. Everything's A-OK. Friendly neighbors there that's where we meet. Can you tell me how to get how to get to Sesame Street! Movin' on up to the east side. We finally got a piece of the pie. It's time to play the music. It's time to light the lights. It's time to meet the Muppets on the Muppet Show tonight. Thank you for being a friend. Travelled down the road and back again. Your heart is true you're a pal and a confidant. The first mate and his Skipper too will do their very best to make the others comfortable in their tropic island nest.
@stop