@extends('main')

@section('content2')
  But they got diff'rent strokes. It takes diff'rent strokes - it takes diff'rent strokes to move the world. Wouldn't you like to get away? Sometimes you want to go where everybody knows your name. And they're always glad you came.<br>
<br>
Just sit right back and you'll hear a tale a tale of a fateful trip that started from this tropic port aboard this tiny ship. But they got diff'rent strokes. It takes diff'rent strokes - it takes diff'rent strokes to move the world. Its mission - to explore strange new worlds to seek out new life and new civilizations to boldly go where no man has gone before. They call him Flipper Flipper faster than lightning. No one you see is smarter than he., Makin their way the only way they know how. That's just a little bit more than the law will allow. And when the odds are against him and their dangers work to do. You bet your life Speed Racer he will see it through. They call him Flipper Flipper faster than lightning. No one you see is smarter than he. Come and knock on our door. We've been waiting for you. Where the kisses are hers and hers and his. Three's company too. But they got diff'rent strokes. It takes diff'rent strokes - it takes diff'rent strokes to move the world? If you have a problem if no one else can help and if you can find them maybe you can hire The A-Team. They call him Flipper Flipper faster than lightning. No one you see is smarter than he.<br>
<br>
They're creepy and they're kooky mysterious and spooky. They're all together ooky the Addams Family. black gold Wouldn't you like to get away? Sometimes you want to go where everybody knows your name. And they're always glad you came. Thank you for being a friend. Travelled down the road and back again. Your heart is true you're a pal and a confidant. Didn't need no welfare states. Everybody pulled his weight. Gee our old Lasalle ran great. Those were the days. So lets make the most of this beautiful day. Since we're together Baby if you've ever wondered - wondered whatever became of me. I'm living on the air in Cincinnati. Cincinnati WKRP. Believe it or not I'm walking on air. I never thought I could feel so free. And you know where you were then. Girls were girls and men were men. Mister we could use a man like Herbert Hoover again. A man is born he's a man of means. Then along come two they got nothin' but their jeans!<br>
<br>
Come and dance on our floor. Take a step that is new. We've a loveable space that needs your face threes company too. black gold Makin their way the only way they know how. That's just a little bit more than the law will allow. Wouldn't you like to get away? Sometimes you want to go where everybody knows your name. And they're always glad you came. Come and play. Everything's A-OK. Friendly neighbors there that's where we meet. Can you tell me how to get how to get to Sesame Street. No phone no lights no motor car not a single luxury. Like Robinson Crusoe it's primitive as can be. Texas tea. Sunday Monday Happy Days. Tuesday Wednesday Happy Days. Thursday Friday Happy Days.Saturday what a day. Groovin' all week with you! The weather started getting rough - the tiny ship was tossed. If not for the courage of the fearless crew the Minnow would be lost. the Minnow would be lost. Knight Rider: A shadowy flight into the dangerous world of a man who does not exist. Come and listen to a story about a man named Jed - a poor mountaineer barely kept his family fed.<br>
<br>
Didn't need no welfare states. Everybody pulled his weight. Gee our old Lasalle ran great. Those were the days? Just sit right back and you'll hear a tale a tale of a fateful trip that started from this tropic port aboard this tiny ship. And you know where you were then. Girls were girls and men were men. Mister we could use a man like Herbert Hoover again.
@stop