@extends('main')
@section('content')
Love exciting and new. Come aboard were expecting you. Love life's sweetest reward Let it flow it floats back to you. Didn't need no welfare states. Everybody pulled his weight. Gee our old Lasalle ran great. Those were the days. A man is born he's a man of means. Then along come two they got nothin' but their jeans. Sunday Monday Happy Days. Tuesday Wednesday Happy Days. Thursday Friday Happy Days.Saturday what a day. Groovin' all week with you. And you know where you were then. Girls were girls and men were men. Mister we could use a man like Herbert Hoover again. I have always wanted to have a neighbor just like you. I've always wanted to live in a neighborhood with you?" Till the one day when the lady met this fellow and they knew it was much more than a hunch. On the most sensational inspirational celebrational Muppetational… This is what we call the Muppet Show. Today still wanted by the government they survive as soldiers of fortune. Why do we always come here? I guess well never know. Its like a kind of torture to have to watch the show. Space. The final frontier. These are the voyages of the Starship Enterprise.<br>
<br>
Flying away on a wing and a prayer. Who could it be? Believe it or not its just me. Straightnin' the curves. Flatnin' the hills Someday the mountain might get ‘em but the law never will. These Happy Days are yours and mine Happy Days. Believe it or not I'm walking on air. I never thought I could feel so free.<br>
<br>
The weather started getting rough - the tiny ship was tossed. If not for the courage of the fearless crew the Minnow would be lost. the Minnow would be lost. Doin' it our way. There's nothing we wont try. Never heard the word impossible. This time there's no stopping us. As long as we live its you and me baby. There ain't nothin' wrong with that. Well we're movin' on up to the east side to a deluxe apartment in the sky. On the most sensational inspirational celebrational Muppetational… This is what we call the Muppet Show." So this is the tale of our castaways they're here for a long long time. They'll have to make the best of things its an uphill climb. Just two good ol' boys Never meanin' no harm. Beats all you've ever saw been in trouble with the law since the day they was born.<br>
<br>
These days are all Happy and Free. These days are all share them with me oh baby." I have always wanted to have a neighbor just like you. I've always wanted to live in a neighborhood with you. Makin their way the only way they know how. That's just a little bit more than the law will allow. They call him Flipper Flipper faster than lightning. No one you see is smarter than he. The Brady Bunch the Brady Bunch that's the way we all became the Brady Bunch.; If you have a problem if no one else can help and if you can find them maybe you can hire The A-Team. Well we're movin' on up to the east side to a deluxe apartment in the sky. Believe it or not I'm walking on air. I never thought I could feel so free. Flying away on a wing and a prayer. Who could it be? Believe it or not its just me. Today still wanted by the government they survive as soldiers of fortune., Believe it or not I'm walking on air. I never thought I could feel so free. Were gonna do it. Give us any chance well take it. Give us any rule we'll break it. We're gonna make our dreams come true. Its mission - to explore strange new worlds to seek out new life and new civilizations to boldly go where no man has gone before. Now were up in the big leagues getting' our turn at bat. Come and knock on our door. We've been waiting for you. Where the kisses are hers and hers and his. Three's company too.<br>
<br>
we might as well say... Would you be mine? Could you be mine? Won't you be my neighbor. Here's the story of a man named Brady who was busy with three boys of his own. And you know where you were then. Girls were girls and men were men. Mister we could use a man like Herbert Hoover again. Just two good ol' boys Wouldn't change if they could. Fightin' the system like a true modern day Robin Hood. Here's the story of a man named Brady who was busy with three boys of his own. Here he comes Here comes Speed Racer. He's a demon on wheels.
@stop